name = "grove.nvim"
description = "Neovim plugin for grove"
type = "go"
managed = true

[binary]
name = "grove-nvim"
path = "./bin/grove-nvim"

[context]
default_rules_path = ".cx/dev-no-tests.rules"
